// viewer.js is a fallback for when index.html hasn't been regenerated by admin.html yet.
// In normal use the admin generates a complete static index.html (like EELabDemos).
// This file only runs if a pre-generated index.html is not present.
(function () {
  'use strict';

  document.getElementById('error').style.display = 'flex';
  document.getElementById('error').textContent =
    'No viewer generated yet. Open admin.html, complete your pairings, and click "Save & Generate Viewer". ' +
    'Then refresh this page.';
  document.getElementById('loading').style.display = 'none';
})();
